#> Database settings.
#> If you don't know what that means, don't touch this section.
#> For more information, please visit the LoginSecurity wiki.
#>
#> Available platforms:
#> - sqlite (default)
#> - mysql

# Global settings
platform: sqlite

# Platform/advanced configuration
configuration:
  sqlite:
    ping-timeout: 5
  mysql:
    host: 'localhost'
    port: 3306
    # Tables are prefixed with ls_
    database: 'minecraft'
    user: 'root'
    password: ''
    ping-timeout: 10
    pool-size: 25
